// One-line, user-facing summary per shipped version, sourced from the vX.Y.Z
// merge-commit subjects (git log) cross-referenced with CHANGELOG.md's own
// per-version date headers -- generated once from git history rather than
// hand-written, since every past release already has a concise summary as
// its commit subject. Ship a new version by appending one entry here (see
// CLAUDE.md's backlog-shipping steps) rather than parsing CHANGELOG.md's
// full bullet-point detail at runtime. `summary` must stay under 75 chars.
export interface ChangelogEntry {
  version: string;
  date: string;
  summary: string;
}

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
  { version: "0.84.13", date: "2026-09-02", summary: "Monitoring overview dashboard; Locations sub-nav + troubleshooting merge" },
  { version: "0.84.12", date: "2026-09-02", summary: "Capped changelog entry summaries at 75 characters" },
  { version: "0.84.11", date: "2026-09-02", summary: "Added Geoapify/OSM attribution + privacy disclosure; Places migration done" },
  { version: "0.84.10", date: "2026-09-02", summary: "Removed disposable Places migration backfill tooling; cleaned stale refs" },
  { version: "0.84.9", date: "2026-09-02", summary: "Places failure logs now show request details, env, and app version" },
  { version: "0.84.8", date: "2026-09-02", summary: "Places monitoring now tracks Geoapify daily credits, not $ estimates" },
  { version: "0.84.7", date: "2026-09-02", summary: "Venue map + boundary drawing now use MapLibre GL + Geoapify tiles" },
  { version: "0.84.6", date: "2026-09-02", summary: "Geoapify migration tool: distance guardrail, coord matching, donut chart" },
  { version: "0.84.5", date: "2026-08-28", summary: "Venue sync, search, and enrichment now run on Geoapify, not Google" },
  { version: "0.84.4", date: "2026-08-28", summary: "Removed ratings, reviews, and photo galleries from venue/POI pages" },
  { version: "0.84.3", date: "2026-08-28", summary: "Behind-the-scenes: remapped category taxonomy for Geoapify move" },
  { version: "0.84.2", date: "2026-08-27", summary: "Behind-the-scenes: started moving venue data off Google Places API" },
  { version: "0.84.1", date: "2026-08-26", summary: "Notification toggles in Account Settings stay hidden until push is on" },
  { version: "0.84.0", date: "2026-08-25", summary: "Places monitoring shows cost/free-tier usage; photo galleries capped at 4" },
  { version: "0.83.0", date: "2026-08-25", summary: "Monitoring tab split into Overview/Performance/Google Places pages" },
  { version: "0.82.0", date: "2026-08-25", summary: "Super-admin Users table gets actions menu and Last login column" },
  { version: "0.81.0", date: "2026-08-25", summary: "Badges and challenges can now be scoped to a single neighborhood" },
  { version: "0.80.0", date: "2026-08-24", summary: "Activity avatars show mushroom look; component lib moved to admin-only" },
  { version: "0.79.0", date: "2026-08-24", summary: "Admin can activate neighborhoods; auto-derived slugs; form polish" },
  { version: "0.78.0", date: "2026-08-23", summary: "Colored ring + corner glyph badges distinguish icon types at a glance" },
  { version: "0.77.0", date: "2026-08-23", summary: "Public profile redesign: Top Caps section, share button, new badges" },
  { version: "0.76.0", date: "2026-08-23", summary: "Location page redesign: tab bar, new Leaderboard tab, Top Caps" },
  { version: "0.75.0", date: "2026-08-23", summary: "Neighborhood page redesign: Top Caps; neighborhoods now collectible" },
  { version: "0.74.1", date: "2026-08-22", summary: "Account page redesign: progress ring, stat strip, card collection" },
  { version: "0.74.0", date: "2026-08-22", summary: "Push alert when a followed event starts soon; new notif toggles" },
  { version: "0.73.0", date: "2026-08-22", summary: "Marketing homepage revamp: mushroom decor, new sections, 404 page" },
  { version: "0.72.0", date: "2026-08-22", summary: "Added \"Continue with Microsoft\" sign-in for login and signup" },
  { version: "0.71.1", date: "2026-08-21", summary: "Fixed venue/POI enrichment refresh, broken against Places API" },
  { version: "0.71.0", date: "2026-08-21", summary: "Super-admin Monitoring tab: errors, latency, Places calls, 404 page" },
  { version: "0.70.0", date: "2026-08-21", summary: "Analytics tab for business admins: check-ins, coupon claims over time" },
  { version: "0.69.0", date: "2026-08-21", summary: "Analytics tab for neighborhood admins: check-ins, category breakdown" },
  { version: "0.68.1", date: "2026-08-20", summary: "Added CI checks; fixed 14 flaky tests and 10 React strict-mode bugs" },
  { version: "0.68.0", date: "2026-08-20", summary: "Collection detail modal, deep-linked push notifications, Next 16.3.1" },
  { version: "0.67.0", date: "2026-08-19", summary: "Getting-started checklist, push opt-in banner, clickable stat tiles" },
  { version: "0.66.0", date: "2026-08-18", summary: "New Forager collection tab: check-ins/connections collect species" },
  { version: "0.65.0", date: "2026-08-17", summary: "Leaderboard is its own tab again; default tab renamed Spore feed" },
  { version: "0.64.0", date: "2026-08-17", summary: "Report a missing venue; admins get a triage page to investigate" },
  { version: "0.63.0", date: "2026-08-17", summary: "Admin is now mobile-friendly; followed events surface in Spore Feed" },
  { version: "0.62.0", date: "2026-08-16", summary: "10 new mushroom silhouettes; Users list gets mushroom/signup/push cols" },
  { version: "0.61.0", date: "2026-08-16", summary: "\"Top Cap\" wooden sign names top visitor on mushroom mosaics" },
  { version: "0.60.1", date: "2026-08-16", summary: "Fixed hydration crash on event/timeline dates; removed no-op SW code" },
  { version: "0.60.0", date: "2026-08-15", summary: "Mushroom mosaics now reflect last 60 days of activity, repeat visits" },
  { version: "0.59.2", date: "2026-08-15", summary: "Feedback tab badge, consistent button styling, review dates + cap" },
  { version: "0.59.1", date: "2026-08-15", summary: "Fixed POIs missing from check-in page; Locations list now A-Z" },
  { version: "0.59.0", date: "2026-08-14", summary: "Super-admin Feedback tab; push alerts on new submissions" },
  { version: "0.58.0", date: "2026-08-14", summary: "Push alerts for neighbor check-ins, connection requests, signups" },
  { version: "0.57.0", date: "2026-08-14", summary: "PWA install prompt, web push, super-admin test-send tool" },
  { version: "0.56.0", date: "2026-08-14", summary: "Super-admin UI: user list, category taxonomy, per-neighborhood Places" },
  { version: "0.55.2", date: "2026-07-29", summary: "Username field accepts uppercase; dropped unused phone column" },
  { version: "0.55.1", date: "2026-07-29", summary: "Marketing homepage polish: real Phinneywood data, honest pilot copy" },
  { version: "0.55.0", date: "2026-07-29", summary: "Feedback submissions with badges; level threshold raised to 100" },
  { version: "0.54.0", date: "2026-07-20", summary: "Venue coupons: check-in-gated claiming, slide-to-redeem" },
  { version: "0.53.1", date: "2026-07-20", summary: "Business claims now require an account; theme/timestamp fixes" },
  { version: "0.53.0", date: "2026-07-17", summary: "Follow events, event/connection feeds, Event Scout badge" },
  { version: "0.52.1", date: "2026-07-17", summary: "Browse-only signed-out flow; fixed email-confirmation login bug" },
  { version: "0.52.0", date: "2026-07-16", summary: "FAQ page, in-app changelog, Places attribution, sort fix" },
  { version: "0.51.0", date: "2026-07-16", summary: "iCal/webcal event feed import, neighborhood-admin Events tab" },
  { version: "0.50.0", date: "2026-07-16", summary: "Neighborhood switcher, unified account menu, merged mushroom fields" },
  { version: "0.49.0", date: "2026-07-15", summary: "Neighborhood join prompt, POI type removal, mushroom loader" },
  { version: "0.48.0", date: "2026-07-15", summary: "Reimport Locations button, super admin role, dense-area sync fix" },
  { version: "0.47.0", date: "2026-07-15", summary: "Mushroom fingerprint stamps on connections and check-ins" },
  { version: "0.46.2", date: "2026-07-15", summary: "Google auth branding, admin logo/pill fixes, live-counted POI challenge" },
  { version: "0.46.1", date: "2026-07-14", summary: "Unify business and neighborhood admin under /admin" },
  { version: "0.46.0", date: "2026-07-14", summary: "In-progress challenges, forager/founder/neighbor badges, gamification fix" },
  { version: "0.45.0", date: "2026-07-14", summary: "Mushroom avatar customizer, spot redesign, expanded palette, rebrand" },
  { version: "0.44.1", date: "2026-07-13", summary: "Neighborhood-admin dashboard redesign, Locations tab improved, bug fixes" },
  { version: "0.44.0", date: "2026-07-13", summary: "GA4 analytics, SEO metadata/sitemaps/robots.txt, Terms & Privacy" },
  { version: "0.43.0", date: "2026-07-13", summary: "Public profiles, profile gating, check-in unlock animations, tab tweaks" },
  { version: "0.42.0", date: "2026-07-12", summary: "Connect with other users, activity feed links, neighbor rewards" },
  { version: "0.41.1", date: "2026-07-12", summary: "Neighborhood/location summary cards, growing fields, check-in counts" },
  { version: "0.41.0", date: "2026-07-12", summary: "Mushroom avatars, growing summary card field, badges/challenges stats" },
  { version: "0.40.0", date: "2026-07-11", summary: "Badge rule engine, check-in result card, Summer Series challenges" },
  { version: "0.39.0", date: "2026-07-10", summary: "Happening now, Recent activity, and reworked neighborhood tabs" },
  { version: "0.38.0", date: "2026-07-10", summary: "Venue and POI merged into one location entity, kind switching" },
  { version: "0.37.0", date: "2026-07-10", summary: "Brand guidelines page, spotted mushroom logo, new favicon/app icon" },
  { version: "0.36.0", date: "2026-07-09", summary: "Marketing site split into apps/marketing, dedicated /checkin page" },
  { version: "0.35.1", date: "2026-07-09", summary: "Profile check-in timeline, comprehensive theme migration, and map theme fix" },
  { version: "0.35.0", date: "2026-07-09", summary: "Marketing homepage, All neighborhoods search + counts" },
  { version: "0.34.0", date: "2026-07-09", summary: "Hamburger menu, theme picker, /neighborhoods split, unified check-in" },
  { version: "0.33.0", date: "2026-07-09", summary: "Spored visual rebrand with dark theme support" },
  { version: "0.32.1", date: "2026-07-08", summary: "Expand Google Places field mask (hours, contact, multi-photo/review)" },
  { version: "0.32.0", date: "2026-07-08", summary: "Fix check-ins from a newly-linked device not attributing to the account" },
  { version: "0.31.0", date: "2026-07-08", summary: "Badges on public profile and account pages" },
  { version: "0.30.0", date: "2026-07-08", summary: "POI landing pages, profile stat cards" },
  { version: "0.29.0", date: "2026-07-09", summary: "Bulk Google Places review and boundary redraw reconciliation" },
  { version: "0.28.0", date: "2026-07-09", summary: "Locations tab: full POI management, merged with venues" },
  { version: "0.27.0", date: "2026-07-08", summary: "Venue omission and reclassification" },
  { version: "0.26.0", date: "2026-07-08", summary: "Admin portal neighborhood boundary drawing, check-in cooldown message fix" },
  { version: "0.25.1", date: "2026-07-08", summary: "Badge icons, neighborhood page subnav tabs, tighter mobile padding" },
  { version: "0.25.0", date: "2026-07-08", summary: "Fix check-in points not being awarded" },
  { version: "0.24.0", date: "2026-07-07", summary: "Account settings page, founding member badge, points backfill" },
  { version: "0.23.0", date: "2026-07-07", summary: "Account page profile summary + nearest-venue check-in, proximity sort" },
  { version: "0.22.0", date: "2026-07-07", summary: "Challenges, points, and neighborhood leaderboard" },
  { version: "0.21.0", date: "2026-07-07", summary: "Public user profiles, Google avatar seeding" },
  { version: "0.20.0", date: "2026-07-07", summary: "User profiles, homepage blurb, version footer" },
  { version: "0.19.0", date: "2026-07-07", summary: "Neighborhood-admin unification, slug URLs, join-button fix, docs reorg" },
  { version: "0.18.0", date: "2026-07-07", summary: "Instagram links and social media integration" },
  { version: "0.17.0", date: "2026-07-06", summary: "Category taxonomy management" },
  { version: "0.16.2", date: "2026-07-07", summary: "Venues on the neighborhood page, home link fix, dark mode form fix" },
  { version: "0.16.1", date: "2026-07-06", summary: "Fix landing page showing no neighborhoods in production" },
  { version: "0.16.0", date: "2026-07-06", summary: "Neighborhoods on landing page and user profile" },
  { version: "0.15.0", date: "2026-07-07", summary: "Neighborhood profile pages" },
  { version: "0.14.1", date: "2026-07-06", summary: "Fix business claims not linking to submitter's account" },
  { version: "0.14.0", date: "2026-07-06", summary: "Business owner venue dashboard" },
  { version: "0.13.0", date: "2026-07-06", summary: "My account page" },
  { version: "0.12.0", date: "2026-07-06", summary: "Neighborhood admin roles" },
  { version: "0.11.0", date: "2026-07-06", summary: "Category mapping admin tool" },
  { version: "0.10.0", date: "2026-07-06", summary: "Google social sign-in + account promotion" },
  { version: "0.9.0", date: "2026-07-06", summary: "Favorite venues" },
  { version: "0.8.0", date: "2026-07-06", summary: "Real user authentication" },
  { version: "0.7.0", date: "2026-07-06", summary: "Venues map view" },
  { version: "0.6.0", date: "2026-07-06", summary: "Business claiming + GPS check-in" },
  { version: "0.5.2", date: "2026-07-06", summary: "Fix venue photos rendering as broken images in production" },
  { version: "0.5.1", date: "2026-07-06", summary: "Fix deployed API 502 on all routes due to eager Supabase client init" },
  { version: "0.5.0", date: "2026-07-06", summary: "Venue detail pages with on-demand enrichment cache" },
  { version: "0.4.1", date: "2026-07-06", summary: "Fix deployed API health check unreachable at localhost" },
  { version: "0.4.0", date: "2026-07-06", summary: "Google Places sync, dedup, category normalization, grant fixes" },
  { version: "0.3.2", date: "2026-07-05", summary: "Data layer schema scaffold + Netlify build fix, Yelp dropped from plan" },
  { version: "0.3.1", date: "2026-07-05", summary: "Adopt Netlify + Supabase as hosting plan of record" },
  { version: "0.3.0", date: "2026-07-06", summary: "Web app scaffold: Turborepo monorepo, Next.js, Express, shared types" },
  { version: "0.2.0", date: "2026-07-05", summary: "Add backlog system and contributing guide, sequence web app first" },
  { version: "0.1.0", date: "2026-07-05", summary: "Initial commit with build plan README" },
];
