// One-line, user-facing summary per shipped version, sourced from the vX.Y.Z
// merge-commit subjects (git log) cross-referenced with CHANGELOG.md's own
// per-version date headers -- generated once from git history rather than
// hand-written, since every past release already has a concise summary as
// its commit subject. Ship a new version by appending one entry here (see
// CLAUDE.md's backlog-shipping steps) rather than parsing CHANGELOG.md's
// full bullet-point detail at runtime.
export interface ChangelogEntry {
  version: string;
  date: string;
  summary: string;
}

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
  { version: "0.83.0", date: "2026-08-25", summary: "Monitoring tab split into Overview/Performance/Google Places sub-pages with filterable request/Places-failure drill-down; business dashboard gets Coupons/Events tiles and event-follow analytics; profile card drops the redundant Points tile" },
  { version: "0.82.0", date: "2026-08-25", summary: "Super-admin Users table gets a three-dot actions menu (Send Test Push is now a modal with a URL field) and a Last login column; Monitoring tab gains domain/version filters; admin nav now prefers Super Admin mode" },
  { version: "0.81.0", date: "2026-08-25", summary: "Badges and challenges can now be scoped to a single neighborhood, with new super-admin and neighborhood-admin pages to manage them -- neighborhood admins can no longer edit a challenge or its badge once anyone has completed it" },
  { version: "0.80.0", date: "2026-08-24", summary: "Activity feed avatars now show your real mushroom look plus context icons, and the component library moved from a public URL to gated super-admin access" },
  { version: "0.79.0", date: "2026-08-24", summary: "Admin action to activate a neighborhood, auto-derived neighborhood slugs (name-city), and neighborhood creation form polish (state/territory label, country/timezone dropdowns)" },
  { version: "0.78.0", date: "2026-08-23", summary: "Colored ring + corner glyph badges distinguish business/POI/neighborhood icons and collection cards at a glance" },
  { version: "0.77.0", date: "2026-08-23", summary: "Public profile redesign with a Top Caps section and share button, three new \"Top Cap\" leaderboard badges, activity points shown in every feed, a venue leaderboard on the neighborhood Leaderboard tab, and level badges through level 20" },
  { version: "0.76.0", date: "2026-08-23", summary: "Location page redesign with a route-per-tab bar (Spore Feed, About, Reviews, Coupons, Events, and a new Leaderboard tab), plus \"Top Caps\" and an \"Open now\" pill for business/POI pages" },
  { version: "0.75.0", date: "2026-08-23", summary: "Neighborhood page redesign with \"Top Caps\" (top 3 recent visitors, shown on the leaderboard alongside lifetime points), plus neighborhoods are now a collectible forager species" },
  { version: "0.74.1", date: "2026-08-22", summary: "Account page redesign -- level-progress ring on the profile card, a divided stat strip, underline tabs, playing-card-styled collection, and day-grouped activity feeds" },
  { version: "0.74.0", date: "2026-08-22", summary: "Push notification when a followed event is starting soon, plus per-category notification toggles (including new coupons at a favorited venue) in Account Settings" },
  { version: "0.73.0", date: "2026-08-22", summary: "Marketing homepage revamp — sprouting mushroom decorations, notifications and collection sections, and a matching 404 page" },
  { version: "0.72.0", date: "2026-08-22", summary: "Added \"Continue with Microsoft\" sign-in alongside Google, for both login and signup" },
  { version: "0.71.1", date: "2026-08-21", summary: "Fixed venue/POI enrichment refresh, which was failing against Google's Places API on every call" },
  { version: "0.71.0", date: "2026-08-21", summary: "Monitoring tab for super admins -- error tracking, request volume/latency, DB query latency, and Google Places API call charts, rolled on our own Postgres tables rather than a third-party service; also a custom on-brand 404 page" },
  { version: "0.70.0", date: "2026-08-21", summary: "Analytics tab for business admins -- check-ins over time, a check-ins-by-day-of-week chart, and coupon claims over time for their venue" },
  { version: "0.69.0", date: "2026-08-21", summary: "Analytics tab for neighborhood admins -- check-ins over time, a locations-by-category breakdown, and a top-venues leaderboard" },
  { version: "0.68.1", date: "2026-08-20", summary: "Automated lint/typecheck/test checks on every code change (CI), fixed 14 flaky gamification tests and 10 React strict-mode bugs, cleaned up internal links and legal-page text escaping" },
  { version: "0.68.0", date: "2026-08-20", summary: "Collection detail modal with swipeable cards, deep-linked push notifications, Next.js 16.3.1" },
  { version: "0.67.0", date: "2026-08-19", summary: "A \"Getting started\" checklist for new accounts, a proactive push-notification opt-in banner, clickable profile stat tiles, a fixed check-in accordion, and clearer mushroom customizer pickers" },
  { version: "0.66.0", date: "2026-08-18", summary: "New Forager collection tab -- checking in or connecting with a neighbor collects a unique mushroom species you tap to reveal, with a new Collection profile tile and a 10-to-1000-species badge tier" },
  { version: "0.65.0", date: "2026-08-17", summary: "Leaderboard is its own tab again, the neighborhood profile's default tab is now a renamed \"Spore feed\", admin's account menu matches the main nav, and chanterelle/enoki mushrooms support all 6 spot counts" },
  { version: "0.64.0", date: "2026-08-17", summary: "Report a missing venue from Send Feedback or the check-in page, notifying your neighborhood's admins -- who get a triage page with a one-click Google Places investigation tool" },
  { version: "0.63.0", date: "2026-08-17", summary: "Admin surfaces are now mobile-friendly, followed-venue events surface in the Spore Feed, and in-progress events are now followable" },
  { version: "0.62.0", date: "2026-08-16", summary: "Ten new mushroom silhouettes join the generative avatar system, and the super admin Users list gets a mushroom column, signup method, and push status" },
  { version: "0.61.0", date: "2026-08-16", summary: "A \"Top Cap\" wooden sign names the top visitor next to a neighborhood/location's mushroom mosaic, and every profile's own patch" },
  { version: "0.60.1", date: "2026-08-16", summary: "Fixed a hydration crash on event/timeline dates and removed a no-op service worker handler flagged by Chrome" },
  { version: "0.60.0", date: "2026-08-15", summary: "Neighborhood/location mushroom mosaics now reflect the last 60 days of live activity with a size boost for repeat visitors, and profile cards show one live mushroom per neighbor" },
  { version: "0.59.2", date: "2026-08-15", summary: "Feedback tab badge, consistent Join/Favorite/Connect button styling, review dates and a latest-3 cap on venue reviews, dev component library split into linkable per-section URLs" },
  { version: "0.59.1", date: "2026-08-15", summary: "Fixed POIs missing from the check-in page, and made the Locations tab's merged list truly alphabetical" },
  { version: "0.59.0", date: "2026-08-14", summary: "Super admin Feedback tab with push notifications on new submissions, feedback menu color fix" },
  { version: "0.58.0", date: "2026-08-14", summary: "Push notifications for neighbor check-ins, connection requests, and new signups" },
  { version: "0.57.0", date: "2026-08-14", summary: "PWA install prompt and web push notifications, plus a super-admin test-send tool" },
  { version: "0.56.0", date: "2026-08-14", summary: "Super admin interface with a platform user list and category taxonomy, Google Places now scoped per neighborhood, hidden locations included in boundary review" },
  { version: "0.55.2", date: "2026-07-29", summary: "Username field accepts uppercase while typing, dropped unused phone column from user accounts" },
  { version: "0.55.1", date: "2026-07-29", summary: "Marketing homepage polish: real Phinneywood data, honest single-neighborhood pilot messaging, accurate business pitch" },
  { version: "0.55.0", date: "2026-07-29", summary: "Feedback submissions with badges, BETA label, level threshold raised to 100, /account tabs get dedicated URLs" },
  { version: "0.54.0", date: "2026-07-20", summary: "Venue coupons with check-in-gated claiming and slide-to-redeem, replacing business announcements" },
  { version: "0.53.1", date: "2026-07-20", summary: "Business claims require an account, admin claims show the linked account, theme and activity-feed timestamp fixes" },
  { version: "0.53.0", date: "2026-07-17", summary: "Follow events, event/neighbor-connection activity feeds, Event Scout badge, My Activity tab" },
  { version: "0.52.1", date: "2026-07-17", summary: "Browse-only signed-out flow (no more anonymous accounts), email-confirmation login fix" },
  { version: "0.52.0", date: "2026-07-16", summary: "FAQ page, in-app changelog, Google Places attribution, category dropdown sort fix" },
  { version: "0.51.0", date: "2026-07-16", summary: "iCal/webcal event feed import, neighborhood-admin Events tab" },
  { version: "0.50.0", date: "2026-07-16", summary: "Neighborhood switcher, unified account menu, merged mushroom fields, public/mushroom defaults" },
  { version: "0.49.0", date: "2026-07-15", summary: "Neighborhood join prompt + auto-home, POI type removal, mushroom loader, checkin/header polish" },
  { version: "0.48.0", date: "2026-07-15", summary: "Reimport Locations button, super admin role, dense-area sync fix" },
  { version: "0.47.0", date: "2026-07-15", summary: "Mushroom fingerprint stamps on connections and check-ins" },
  { version: "0.46.2", date: "2026-07-15", summary: "Google auth branding, admin logo/pill fixes, live-counted POI challenge" },
  { version: "0.46.1", date: "2026-07-14", summary: "Unify business and neighborhood admin under /admin" },
  { version: "0.46.0", date: "2026-07-14", summary: "In-progress challenges, forager/founder/neighbor badge polish, gamification fixes" },
  { version: "0.45.0", date: "2026-07-14", summary: "Mushroom avatar customizer, spot count/shape redesign, expanded palette, brand refresh" },
  { version: "0.44.1", date: "2026-07-13", summary: "Neighborhood-admin dashboard redesign, Locations tab improvements, bug fixes" },
  { version: "0.44.0", date: "2026-07-13", summary: "GA4 analytics, SEO (metadata/sitemaps/robots.txt/JSON-LD), Terms & Privacy pages" },
  { version: "0.43.0", date: "2026-07-13", summary: "Public profiles, profile gating, check-in unlock animations, account tab improvements" },
  { version: "0.42.0", date: "2026-07-12", summary: "Connect with other users, activity feed links, neighbor rewards" },
  { version: "0.41.1", date: "2026-07-12", summary: "Neighborhood and location summary cards, growing mushroom fields, check-in/favorite counts" },
  { version: "0.41.0", date: "2026-07-12", summary: "Mushroom avatars, profile summary card growing-mushroom field, badges/challenges stats" },
  { version: "0.40.0", date: "2026-07-11", summary: "Badge rule engine, check-in result card, Summer Series challenges" },
  { version: "0.39.0", date: "2026-07-10", summary: "Happening now, Recent activity, and reworked neighborhood tabs" },
  { version: "0.38.0", date: "2026-07-10", summary: "Venue and POI merged into single location entity with in-place kind switching" },
  { version: "0.37.0", date: "2026-07-10", summary: "Brand guidelines page, spotted mushroom logo, new favicon/app icon" },
  { version: "0.36.0", date: "2026-07-09", summary: "Marketing site split into apps/marketing, dedicated /checkin page" },
  { version: "0.35.1", date: "2026-07-09", summary: "Profile check-in timeline, comprehensive theme migration, and map theme fix" },
  { version: "0.35.0", date: "2026-07-09", summary: "Marketing homepage, All neighborhoods search + counts" },
  { version: "0.34.0", date: "2026-07-09", summary: "Hamburger menu with theme picker, /neighborhoods split, unified check-in gesture" },
  { version: "0.33.0", date: "2026-07-09", summary: "Spored visual rebrand with dark theme support" },
  { version: "0.32.1", date: "2026-07-08", summary: "Expand Google Places field mask (hours, contact, multi-photo/review)" },
  { version: "0.32.0", date: "2026-07-08", summary: "Fix check-ins from a newly-linked device not attributing to the account" },
  { version: "0.31.0", date: "2026-07-08", summary: "Badges on public profile and account pages" },
  { version: "0.30.0", date: "2026-07-08", summary: "POI landing pages, profile stat cards" },
  { version: "0.29.0", date: "2026-07-09", summary: "Bulk Google Places review and boundary redraw reconciliation" },
  { version: "0.28.0", date: "2026-07-09", summary: "Locations tab: full POI management, merged with venues" },
  { version: "0.27.0", date: "2026-07-08", summary: "Venue omission and reclassification" },
  { version: "0.26.0", date: "2026-07-08", summary: "Admin portal neighborhood boundary drawing, check-in cooldown message fix" },
  { version: "0.25.1", date: "2026-07-08", summary: "Badge icons, neighborhood page subnav tabs, tighter mobile padding" },
  { version: "0.25.0", date: "2026-07-08", summary: "Fix check-in points not being awarded" },
  { version: "0.24.0", date: "2026-07-07", summary: "Account settings page, founding member badge, points backfill" },
  { version: "0.23.0", date: "2026-07-07", summary: "Account page profile summary + nearest-venue check-in, proximity sort" },
  { version: "0.22.0", date: "2026-07-07", summary: "Challenges, points, and neighborhood leaderboard" },
  { version: "0.21.0", date: "2026-07-07", summary: "Public user profiles, Google avatar seeding" },
  { version: "0.20.0", date: "2026-07-07", summary: "User profiles, homepage blurb, version footer" },
  { version: "0.19.0", date: "2026-07-07", summary: "Neighborhood-admin unification, slug URLs, join-button fix, docs reorg" },
  { version: "0.18.0", date: "2026-07-07", summary: "Instagram links and social media integration" },
  { version: "0.17.0", date: "2026-07-06", summary: "Category taxonomy management" },
  { version: "0.16.2", date: "2026-07-07", summary: "Venues on the neighborhood page, home link fix, dark mode form fix" },
  { version: "0.16.1", date: "2026-07-06", summary: "Fix landing page showing no neighborhoods in production" },
  { version: "0.16.0", date: "2026-07-06", summary: "Neighborhoods on landing page and user profile" },
  { version: "0.15.0", date: "2026-07-07", summary: "Neighborhood profile pages" },
  { version: "0.14.1", date: "2026-07-06", summary: "Fix business claims not linking to submitter's account" },
  { version: "0.14.0", date: "2026-07-06", summary: "Business owner venue dashboard" },
  { version: "0.13.0", date: "2026-07-06", summary: "My account page" },
  { version: "0.12.0", date: "2026-07-06", summary: "Neighborhood admin roles" },
  { version: "0.11.0", date: "2026-07-06", summary: "Category mapping admin tool" },
  { version: "0.10.0", date: "2026-07-06", summary: "Google social sign-in + account promotion" },
  { version: "0.9.0", date: "2026-07-06", summary: "Favorite venues" },
  { version: "0.8.0", date: "2026-07-06", summary: "Real user authentication" },
  { version: "0.7.0", date: "2026-07-06", summary: "Venues map view" },
  { version: "0.6.0", date: "2026-07-06", summary: "Business claiming + GPS check-in" },
  { version: "0.5.2", date: "2026-07-06", summary: "Fix venue photos rendering as broken images in production" },
  { version: "0.5.1", date: "2026-07-06", summary: "Fix deployed API 502 on all routes due to eager Supabase client init" },
  { version: "0.5.0", date: "2026-07-06", summary: "Venue detail pages with on-demand enrichment cache" },
  { version: "0.4.1", date: "2026-07-06", summary: "Fix deployed API health check unreachable at localhost" },
  { version: "0.4.0", date: "2026-07-06", summary: "Google Places sync, dedup, category normalization; Netlify + Supabase grant fixes" },
  { version: "0.3.2", date: "2026-07-05", summary: "Data layer schema scaffold + Netlify build fix, Yelp dropped from plan" },
  { version: "0.3.1", date: "2026-07-05", summary: "Adopt Netlify + Supabase as hosting plan of record" },
  { version: "0.3.0", date: "2026-07-06", summary: "Web app scaffold: Turborepo monorepo with Next.js, Express API, shared types" },
  { version: "0.2.0", date: "2026-07-05", summary: "Add backlog system and contributing guide, sequence web app first" },
  { version: "0.1.0", date: "2026-07-05", summary: "Initial commit with build plan README" },
];
